// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>['id']]

/**
 * Item in *Home → Avatar*
 */
export interface HomeDocumentDataAvatarItem {
  /**
   * Avatar field in *Home → Avatar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.avatar[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>

  /**
   * Is light theme field in *Home → Avatar*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: home.avatar[].is_light_theme
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_light_theme: prismic.BooleanField
}

type HomeDocumentDataSlicesSlice = LinkSlice | SocialMediaLinksSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Avatar field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.avatar[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  avatar: prismic.GroupField<Simplify<HomeDocumentDataAvatarItem>>

  /**
   * User name field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: John Doe
   * - **API ID Path**: home.user_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  user_name: prismic.KeyTextField

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

export type AllDocumentTypes = HomeDocument

/**
 * Item in *Link → Default → Primary → Link*
 */
export interface LinkSliceDefaultPrimaryLinkItem {
  /**
   * URL field in *Link → Default → Primary → Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://github.com/
   * - **API ID Path**: link.default.primary.link[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Title field in *Link → Default → Primary → Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Github link
   * - **API ID Path**: link.default.primary.link[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField
}

/**
 * Primary content in *Link → Default → Primary*
 */
export interface LinkSliceDefaultPrimary {
  /**
   * Link field in *Link → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link.default.primary.link[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  link: prismic.GroupField<Simplify<LinkSliceDefaultPrimaryLinkItem>>
}

/**
 * Default variation for Link Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LinkSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Link*
 */
type LinkSliceVariation = LinkSliceDefault

/**
 * Link Shared Slice
 *
 * - **API ID**: `link`
 * - **Description**: Link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkSlice = prismic.SharedSlice<'link', LinkSliceVariation>

/**
 * Item in *SocialMediaLinks → Default → Primary → Social Media Links*
 */
export interface SocialMediaLinksSliceDefaultPrimarySocialMediaLinksItem {
  /**
   * Logo field in *SocialMediaLinks → Default → Primary → Social Media Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.default.primary.social_media_links[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * URL field in *SocialMediaLinks → Default → Primary → Social Media Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://github.com/
   * - **API ID Path**: social_media_links.default.primary.social_media_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Logo alt field in *SocialMediaLinks → Default → Primary → Social Media Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Github link
   * - **API ID Path**: social_media_links.default.primary.social_media_links[].logo_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  logo_alt: prismic.KeyTextField
}

/**
 * Primary content in *SocialMediaLinks → Default → Primary*
 */
export interface SocialMediaLinksSliceDefaultPrimary {
  /**
   * Social Media Links field in *SocialMediaLinks → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.default.primary.social_media_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_media_links: prismic.GroupField<
    Simplify<SocialMediaLinksSliceDefaultPrimarySocialMediaLinksItem>
  >
}

/**
 * Default variation for SocialMediaLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialMediaLinksSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SocialMediaLinksSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *SocialMediaLinks*
 */
type SocialMediaLinksSliceVariation = SocialMediaLinksSliceDefault

/**
 * SocialMediaLinks Shared Slice
 *
 * - **API ID**: `social_media_links`
 * - **Description**: SocialMediaLinks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialMediaLinksSlice = prismic.SharedSlice<
  'social_media_links',
  SocialMediaLinksSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataAvatarItem,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      LinkSlice,
      LinkSliceDefaultPrimaryLinkItem,
      LinkSliceDefaultPrimary,
      LinkSliceVariation,
      LinkSliceDefault,
      SocialMediaLinksSlice,
      SocialMediaLinksSliceDefaultPrimarySocialMediaLinksItem,
      SocialMediaLinksSliceDefaultPrimary,
      SocialMediaLinksSliceVariation,
      SocialMediaLinksSliceDefault,
    }
  }
}
