// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  link: dynamic(() => import('./Link')),
  social_media_links: dynamic(() => import('./SocialMediaLinks')),
}
